
/* Crete some users for the login */
INSERT INTO `users` (username, password, enabled) VALUES ('bride','$2a$10$CWffHGKToyWE6nc4R0ElyODYO9fgYSiyEMue8wMUXmfNrR1y/4a8G',1);
INSERT INTO `users` (username, password, enabled) VALUES ('groom','$2a$10$YJsUSnCOheVK2xKiEJTHEu/zsa75fvApMFUUBRfBvKIPucJtkju5q',1);
INSERT INTO `users` (username, password, enabled) VALUES ('guest','$2a$10$XLu4xSbgrujPBrSqVGrB1.01TMwpWkDZGeasWKngjql3nyFju9GmC',1);

/* Crete some roles for the user's authorization */
INSERT INTO `authorities` (user_id, authority) VALUES (1,'ROLE_ADMIN');
INSERT INTO `authorities` (user_id, authority) VALUES (2,'ROLE_ADMIN');
INSERT INTO `authorities` (user_id, authority) VALUES (3,'ROLE_USER');

/* Crete a wedding for the index page */
INSERT INTO `db_springboot_app`.`wedding` (`ceremony_description`, `ceremony_hour`, `ceremony_photo`, `ceremony_place`, `party_description`, `party_hour`, `party_photo1`, `party_photo2`, `party_place`) VALUES ('Elegimos la catedral de Pamplona para casarnos porque como todos sabéis  somos Pamplonicas y nos encanta disfrutar de nuestra ciudad y pasear por el casco viejo. Y que mejor lugar que la catedral para celebrar allí este día tan especial para nosotros, que esperemos que también lo sea para cada uno de vosotros. La ceremonia será a las 12:00h y a la salida os tendremos preparada una sorpresa que OS VA A ENCANTAR! Poneros vuestras mejores galas y preparaos para vivir un día lleno de momentos inolvidables! ', '12:00', 'catedral-pamplona.jpg', 'La Catedral de Pamplona', 'Y llegó el momento de la FIESTA!!! Después de la ceremonia (que ya sabemos que no es la parte más divertida del día), nos toca comer y bailar hasta que no podamos más!\nHemos elegido este sitio porque desde el primer momento nos cautivó, ya que siempre habíamos hablado de hacerlo al aire libre.\nPrimero os esperará un lunch a las 14:00 y a las 15:00 nos sentaremos a disfrutar del banquete que no va a dejar indiferente a nadie... y...¿CÓMO VA A FALTAR UNA BUENA FIESTA CON UN DJ QUE PONGA TODOS NUESTROS TEMAS FAVORITOS?', '14:00', 'party.jpg', 'party2.jpg', 'Hotel Alma Pamplona');

/* Crete a history for the index page*/
INSERT INTO `db_springboot_app`.`histories` (`how_meet`, `how_meet_photo`, `time_together`, `time_together_photo`, `wedding_request`, `wedding_request_photo`) VALUES ('Los dos tenemos ahora 27 años, y nos conocimos cuando teníamos 13.\nHabíamos llegado nuevos a un colegio y nos hicimos amigos enseguida. Siempre nos gustamos, pero ninguno se atrevía a dar el paso.\nTuvimos cada uno nuestras parejas, nuestros líos y seguimos siendo amigos mucho tiempo. Después nos distanciamos un poco,\ny después de un año y pico sin vernos nos reencontramos. Los dos solteros. Después de una semana o así, nos dimos nuestro primer beso y así empezo todo...!', 'first-time.jpg', 'Llevamos ya 5 años juntos y estamos igual de ilusionados que el primer día.\nTenemos una relación mágica, sólo con mirarnos nos entendemos y sabemos perfectamente\nque está pensando el otro.\n(OS ESTARÉIS PREGUNTANDO SI DISCUTIMOS...) Pues la respuesta es SÍ, claro que nos\nenfadamos a veces, pero enseguida se nos pasa y luego no podemos estar el uno sin\nel otro. Tenemos caracteres muy distintos, pero nos compenetramos a la perfección y lo más\nimportante de todo NOS QUEREMOS y NOS RESPETAMOS!', 'time.jpg', 'En nuestro quinto aniversario, Mikel me preparó\nuna fiesta sorpresa con nuestra familia y amigos. Al principio me sorprendió porque pensaba que íbamos a estar los dos solos,\npero después lo comprendí todo... Había decorado el lugar con fotos nuestras, con mis flores favoritas (las magnolias),\ny para colmo había encargado la cena a mi restaurante favorito (la Cervecería Babylon), era todo espectacular.\nEstábamos pasandolo genial, riendonos, bailando, abrazándonos... y de repente la música se apagó, miré y Mikel estaba sobre una rodilla. Grité, grité \"SÍ\" y nos comprometimos.\nEstamos muy emocionados de celebrar este próximo capítulo en nuestras vidas con vosotros.\n¡Nos vemos en NUESTRA BODA!', 'ring.jpg');

/* Crete brides the index page */
INSERT INTO `db_springboot_app`.`brides` (`about_her`, `about_him`, `bride_photo`, `groom_photo`, `name_bride`, `name_groom`, `wedding_date`, `id_history`, `id_wedding`) VALUES ('¡Me encanta la vida! ¡Todos los días son una experiencia nueva! ¡Lo que de verdad me llena como persona es ayudar a los demás\ny disfruto viendo a la gente reir y ser feliz! ¡Soy una persona muy honesta que siempre digo lo que pienso, me considero una romántica empedernida\ny una sensiblona (lloro viendo películas de amor)! Soy amante de la naturaleza y de los animales, uno de mis sueños es viajar por el mundo, conocer las diferentes culturas,\nexplorar los sitios más impresionantes del mundo y poder ayudar y proteger a los animales que lo necesiten. Pero, lo que más me define es que soy una persona feliz\nque cree que todos deberíamos parar y disfrutar de la vida siempre que podamos, porque estamos aquí solo por un corto tiempo y dejar la vida pasar sin disfrutar es un desperdicio.\nPodría seguir adelante...., ¡pero ya te haces una idea de cómo soy!', 'Todos los que me conoceís sabeís que si algo me define es que soy una persona segura de si misma, a la que le encanta reir,\ndisrutar de la vida, estar con los míos, superarme cada día en todo lo que pueda y no perder el tiempo en cosas que no merecen la pena.\nSi algo he aprendido a lo largo del tiempo es que lo verdaderemente importante no es sólo llegar a la meta, si no disfrutar del camino y aprender de las piedras que se interponen en él y sobre todo que\nno importa si nos tropezamos, lo importante es saber levantarse con más fuerza.\nAl igual que Alba, me apasiona la naturaleza, me encanta dar paseos por el monte, respirar el aire fresco, disfrutar del silencio y sólo escuchar los sonidos de los animales, de las casacadas, del viento...\ny olvidarme por un momento de todo y disfrutar de ese instante. Pero como ya me conoceís no os voy a aburrir más!', 'she.jpg', 'he.jpg', 'Daniela', 'Fabio', '2021/08/28', '1', '1');

/* Crete memories for the gallery*/
INSERT INTO `memories` VALUES (1,'Quédate con quien te bese el alma, la piel te la puede besar cualquiera.','oporto.jpg','Oporto - Portugal'),(2,'Nuestro amor es como las olas del mar, que aún rompiendo contra las rocas, encuentran fuerzas para volver a empezar!','walking-water.jpg','Caminando sobre las olas'),(3,'A veces... el paraíso... es apoyar la cabeza en el hombro correcto...','paris.jpg','París - Francia'),(4,'El amor crea puentes en lugares que parecen imposibles de cruzar...','santa-monica.jpg','Santa Mónica - California'),(5,'Y es que el amor no necesita ser entendido... sólo necesita ser demostrado...','sunshine.jpg','El amanecer más bonito'),(6,'Abrázame... Hasta vencer nuestros miedos... Hasta romper las barreras... Hasta llenarnos el corazón... Simplemente abrázame...','schlegeisstausee_ austria.jpg','Schlegeis Stausee - Austria'),(7,'El verdadero amor es elegir a una persona y volver a elegirla todos los días...','cianorte-brazil.jpg','Cianorte - Brasil'),(8,'Y es que el amor no necesita ser entendido... sólo necesita ser demostrado...','asilah-morocco.jpg','Asilah - Morocco'),(9,'Tengo ganas de besarte, de tomarte de la mano y huir contigo del mundo. O sencillamente abrazarte y decirte al oído: Por favor no me sueltes...','iceland.jpg','Islandia');

/* Crete a family to show in the index page */
INSERT INTO `family` VALUES (1,'Meritxell Oliveira','mum_her.jpg','Madre de la novia'),(2,'Alfonso Sainz','dad_her.jpg','Padre de la novia'),(3,'Sara Sainz','sara.jpg','Hermana de la novia'),(4,'Alex Leiva','alex.jpg','Mejor amigo de la novia'),(5,'Leila Herranz','mum_him.jpg','Madre del novio'),(6,'Nicolás Viñas','dad_him.jpg','Padre del novio'),(7,'Carla Viñas','carla.jpg','Hermana del novio'),(8,'Raúl Bonet','raul.jpg','Mejor amigo del novio');

/* Crete some guests for the guest list */
INSERT INTO `guests` VALUES (1,'Voy a asistir a todo','2020-06-09','alba2991@gmail.com','Alba Serrano'),(2,'Iré después al banquete y la fiesta','1993-01-08','mikel.rivero.usunariz@gmail.com','Mikel Rivero'),(3,'Iré sólo a la ceremonia','1944-02-14','jmolaz@gmail.com','Juana mary '),(4,'Iré sólo a la ceremonia','2007-01-01','alba2991@gmail.com','Alba Serrano');

INSERT INTO `tasks` (description, budget) VALUES ('mandar las invitaciones', 200);
INSERT INTO `tasks` (description, budget) VALUES ('Elegir fecha boda', 0.0);
INSERT INTO `tasks` (description, budget) VALUES ('Elegir la orquesta para la fiesta', 2050);
INSERT INTO `tasks` (description, budget) VALUES ('Elegir las flores de la ceremonia', 500.50);
INSERT INTO `tasks` (description, budget) VALUES ('Elegir catering banquete', 10000);